//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEDETAIL
    {
        public int EMP_EMPLOYEEID { get; set; }
        public string EMP_EMPLOYEENAME { get; set; }
        public string EMP_EMPLOYEEEMAILID { get; set; }
        public string EMP_EMPLOYEEPHONENUMBER { get; set; }
        public string EMP_CREATEDBY { get; set; }
        public System.DateTime EMP_CREATEDDATE { get; set; }
        public System.DateTime EMP_UPDATEDDATE { get; set; }
        public int EMP_STATUS { get; set; }
        public string EMP_UPDATEDBY { get; set; }
    }
}
