//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMAILTEMPLATESEntities : DbContext
    {
        public EMAILTEMPLATESEntities()
            : base("name=EMAILTEMPLATESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLOYEEDETAIL> EMPLOYEEDETAILS { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATES { get; set; }
    
        public virtual int ASP_INSERT_EMPLOYEEE(string eMP_EMPLOYEENAME, string eMP_EMPLOYEEEMAILID, string eMP_EMPLOYEEPHONENUMBER)
        {
            var eMP_EMPLOYEENAMEParameter = eMP_EMPLOYEENAME != null ?
                new ObjectParameter("EMP_EMPLOYEENAME", eMP_EMPLOYEENAME) :
                new ObjectParameter("EMP_EMPLOYEENAME", typeof(string));
    
            var eMP_EMPLOYEEEMAILIDParameter = eMP_EMPLOYEEEMAILID != null ?
                new ObjectParameter("EMP_EMPLOYEEEMAILID", eMP_EMPLOYEEEMAILID) :
                new ObjectParameter("EMP_EMPLOYEEEMAILID", typeof(string));
    
            var eMP_EMPLOYEEPHONENUMBERParameter = eMP_EMPLOYEEPHONENUMBER != null ?
                new ObjectParameter("EMP_EMPLOYEEPHONENUMBER", eMP_EMPLOYEEPHONENUMBER) :
                new ObjectParameter("EMP_EMPLOYEEPHONENUMBER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ASP_INSERT_EMPLOYEEE", eMP_EMPLOYEENAMEParameter, eMP_EMPLOYEEEMAILIDParameter, eMP_EMPLOYEEPHONENUMBERParameter);
        }
    
        public virtual int ASP_UPDATE_EMPLOYEE(Nullable<int> eMP_EMPLOYEEID, string eMP_EMPLOYEENAME, string eMP_EMPLOYEEEMAILID, string eMP_EMPLOYEEPHONENUMBER, string eMP_UPDATEDBY)
        {
            var eMP_EMPLOYEEIDParameter = eMP_EMPLOYEEID.HasValue ?
                new ObjectParameter("EMP_EMPLOYEEID", eMP_EMPLOYEEID) :
                new ObjectParameter("EMP_EMPLOYEEID", typeof(int));
    
            var eMP_EMPLOYEENAMEParameter = eMP_EMPLOYEENAME != null ?
                new ObjectParameter("EMP_EMPLOYEENAME", eMP_EMPLOYEENAME) :
                new ObjectParameter("EMP_EMPLOYEENAME", typeof(string));
    
            var eMP_EMPLOYEEEMAILIDParameter = eMP_EMPLOYEEEMAILID != null ?
                new ObjectParameter("EMP_EMPLOYEEEMAILID", eMP_EMPLOYEEEMAILID) :
                new ObjectParameter("EMP_EMPLOYEEEMAILID", typeof(string));
    
            var eMP_EMPLOYEEPHONENUMBERParameter = eMP_EMPLOYEEPHONENUMBER != null ?
                new ObjectParameter("EMP_EMPLOYEEPHONENUMBER", eMP_EMPLOYEEPHONENUMBER) :
                new ObjectParameter("EMP_EMPLOYEEPHONENUMBER", typeof(string));
    
            var eMP_UPDATEDBYParameter = eMP_UPDATEDBY != null ?
                new ObjectParameter("EMP_UPDATEDBY", eMP_UPDATEDBY) :
                new ObjectParameter("EMP_UPDATEDBY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ASP_UPDATE_EMPLOYEE", eMP_EMPLOYEEIDParameter, eMP_EMPLOYEENAMEParameter, eMP_EMPLOYEEEMAILIDParameter, eMP_EMPLOYEEPHONENUMBERParameter, eMP_UPDATEDBYParameter);
        }
    
        public virtual int ASP_DELETE_EMPLOYEE(Nullable<int> eMP_EMPLOYEEID)
        {
            var eMP_EMPLOYEEIDParameter = eMP_EMPLOYEEID.HasValue ?
                new ObjectParameter("EMP_EMPLOYEEID", eMP_EMPLOYEEID) :
                new ObjectParameter("EMP_EMPLOYEEID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ASP_DELETE_EMPLOYEE", eMP_EMPLOYEEIDParameter);
        }
    
        public virtual ObjectResult<ASP_BIND_EMPLOYEEDETAILS_Result> ASP_BIND_EMPLOYEEDETAILS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ASP_BIND_EMPLOYEEDETAILS_Result>("ASP_BIND_EMPLOYEEDETAILS");
        }
    }
}
