//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public int TMP_SNO { get; set; }
        public string TMP_TEMPLATENAME { get; set; }
        public string TMP_SROURCECODE { get; set; }
        public string TMP_CREATEDBY { get; set; }
        public System.DateTime TMP_CREATEDDATE { get; set; }
        public string TMP_UPDATEDBY { get; set; }
        public System.DateTime TMP_UPDATEDDATE { get; set; }
        public int TMP_STATUS { get; set; }
    }
}
